version: "3.9"

services:
  # hookdeck container
  hookdeck:
   container_name: hookdeck
   image: hookdeck/hookdeck-cli:v1.5.0
   entrypoint: ["/bin/sh", "-c"]
   command:
     - |
       # Check for existing config, log in if needed
       [ -f $HOME/.config/hookdeck/config.toml ] && echo "Hookdeck config found!" || /bin/hookdeck login
       # Start the listen command
       /bin/hookdeck listen app:8000 telegram
   volumes:
     - hookdeck_data:/root/.config/hookdeck
   networks:
     - network
   tty: true
   restart: always

  # Redis container
  redis:
    container_name: redis
    image: redis/redis-stack:7.4.0-v8
    networks:
      - network
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always

  # RDBMS container
  db:
    container_name: db
    image: postgres:14.17-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: consigliere
      POSTGRES_USER: consigliere
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password
    restart: always

  # LLM provider
  ollama:
    container_name: ollama
    image: ollama/ollama:0.13.4
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  app:
    container_name: app
    build: .
    volumes:
      - knowledge_data:/app/data/knowledge
    networks:
      - network
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - redis
      - hookdeck
      - db
      - ollama

  # Defines the nginx container, which acts as the API gateway.
  nginx:
    container_name: nginx
    image: nginx:1.29.4-trixie-perl
    ports:
      - "80:80"
    volumes:
      - nginx_data:/etc/nginx
    networks:
      - network
    depends_on:
      - app

volumes:
  postgres_data:
    external: true
  hookdeck_data:
    external: true
  knowledge_data:
    external: true
  nginx_data:
    external: true
  ollama_data:
    external: true

networks:
  network:

secrets:
   db_password:
     file: postgres.txt
