version: "3.9"

services:
  # LLM provider
  ollama:
    container_name: ollama
    image: ollama/ollama:0.12.11
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data:
    external: true
